# Generated by Django 3.2 on 2022-09-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220903_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='postcode',
            field=models.CharField(max_length=20),
        ),
    ]
