# Generated by Django 3.2 on 2022-09-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergy_info',
        ),
        migrations.AddField(
            model_name='product',
            name='allergy_info',
            field=models.ManyToManyField(blank=True, null=True, to='products.Allergy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default='100', null=True),
        ),
    ]
