# Generated by Django 3.2 on 2022-09-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
    ]
